services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_DATABASE=event-booking-app
      - DB_USERNAME=user
      - DB_PASSWORD=pass
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    working_dir: /var/www
    command: >
      sh -c "composer install &&
             php artisan key:generate &&
             php artisan config:clear &&
             php artisan migrate --force &&
             php artisan storage:link &&
             php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: event-booking-app
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
